#!/bin/bash

BUILD_OUTPUT="$(go build -o app .)"

if [[ "$?" -ne "" ]]; then
  echo $BUILD_OUTPUT
  exit 1
fi

if [[ ! -f "app" ]]; then
  echo "Error: app executable missing"
  exit 1
else
    sudo env $(cat secrets) ./app
fi
